import { createPublicKey, createSign, generateKeyPairSync, sign } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

function options(args) {
  const values = new Map();
  for (let index = 0; index < args.length; index += 1) {
    if (!args[index].startsWith("--")) continue;
    values.set(args[index].slice(2), args[index + 1]);
    index += 1;
  }
  return values;
}

function required(values, name) {
  const value = values.get(name);
  if (!value || value.startsWith("--")) throw new Error(`缺少 --${name}`);
  return value;
}

function writePublicKeyModule(target, rsaPublicKey, ed25519PublicKey) {
  const source = [
    "// Generated by `npm run license:keygen`. Never store the matching private key in the repository.",
    `export const LICENSE_PUBLIC_KEY = ${JSON.stringify(rsaPublicKey)};`,
    `export const LICENSE_ED25519_PUBLIC_KEY = ${JSON.stringify(ed25519PublicKey)};`,
    "",
  ].join("\n");
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, source, "utf8");
}

function ensureKeyPair(privateKeyPath, type) {
  if (existsSync(privateKeyPath)) {
    const privateKey = readFileSync(privateKeyPath);
    return {
      privateKey,
      publicKey: createPublicKey(privateKey).export({ type: "spki", format: "pem" }).toString(),
      created: false,
    };
  }
  const options = type === "rsa"
    ? { modulusLength: 3072, publicKeyEncoding: { type: "spki", format: "pem" }, privateKeyEncoding: { type: "pkcs8", format: "pem" } }
    : { publicKeyEncoding: { type: "spki", format: "pem" }, privateKeyEncoding: { type: "pkcs8", format: "pem" } };
  const { privateKey, publicKey } = generateKeyPairSync(type, options);
  mkdirSync(path.dirname(privateKeyPath), { recursive: true });
  writeFileSync(privateKeyPath, privateKey, { mode: 0o600 });
  return { privateKey, publicKey, created: true };
}

function keygen(values) {
  const rsaPrivateKeyPath = path.resolve(values.get("private-key") ?? values.get("rsa-private-key") ?? ".local/license-private-key.pem");
  const ed25519PrivateKeyPath = path.resolve(values.get("ed25519-private-key") ?? ".local/license-ed25519-private-key.pem");
  const publicKeySource = path.resolve(values.get("public-key-source") ?? "electron/license-public-key.ts");
  const rsa = ensureKeyPair(rsaPrivateKeyPath, "rsa");
  const ed25519 = ensureKeyPair(ed25519PrivateKeyPath, "ed25519");
  writePublicKeyModule(publicKeySource, rsa.publicKey, ed25519.publicKey);
  console.log(`${rsa.created ? "RSA 私钥已写入" : "RSA 私钥已保留"}: ${rsaPrivateKeyPath}`);
  console.log(`${ed25519.created ? "Ed25519 私钥已写入" : "Ed25519 私钥已保留"}: ${ed25519PrivateKeyPath}`);
  console.log(`公钥模块已写入: ${publicKeySource}`);
}

function expiryDay(expiresAt) {
  if (!expiresAt) return 0;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(expiresAt)) throw new Error("--expires 必须是 YYYY-MM-DD");
  const timestamp = Date.parse(`${expiresAt}T00:00:00.000Z`);
  if (Number.isNaN(timestamp) || new Date(timestamp).toISOString().slice(0, 10) !== expiresAt) {
    throw new Error("--expires 必须是有效日期");
  }
  return Math.floor(timestamp / 86_400_000);
}

function installationIdBytes(installId) {
  const compact = installId.replace(/-/g, "");
  if (!/^[a-f0-9]{32}$/i.test(compact)) throw new Error("--install-id 必须是应用设置页显示的 UUID");
  return Buffer.from(compact, "hex");
}

function compactCode(payload, privateKey) {
  const signed = Buffer.concat([payload, sign(null, payload, privateKey)]);
  const encoded = signed.toString("base64url").replaceAll("-", "~");
  return `P2-${encoded.match(/.{1,5}/g).join("-")}`;
}

function issueCompact(values, installId, expiresAt, maxConcurrentRunners) {
  const privateKeyPath = path.resolve(values.get("ed25519-private-key") ?? ".local/license-ed25519-private-key.pem");
  const expires = Boolean(expiresAt);
  const payload = Buffer.alloc(23);
  payload[0] = 2;
  payload[1] = expires ? 1 : 0;
  installationIdBytes(installId).copy(payload, 2);
  payload.writeUInt32BE(expiryDay(expiresAt), 18);
  payload[22] = maxConcurrentRunners;
  console.log(compactCode(payload, readFileSync(privateKeyPath)));
}

function issueLegacy(values, installId, expiresAt, maxConcurrentRunners) {
  const privateKeyPath = path.resolve(values.get("private-key") ?? values.get("rsa-private-key") ?? ".local/license-private-key.pem");
  const payload = {
    version: 1,
    tier: "pro",
    installId,
    issuedAt: new Date().toISOString(),
    ...(expiresAt ? { expiresAt } : {}),
    maxConcurrentRunners,
  };
  const encodedPayload = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const signer = createSign("RSA-SHA256");
  signer.update(encodedPayload);
  signer.end();
  console.log(`${encodedPayload}.${signer.sign(readFileSync(privateKeyPath), "base64url")}`);
}

function issue(values) {
  const installId = required(values, "install-id");
  const expiresAt = values.get("expires");
  const maxConcurrentRunners = Number(values.get("max-runners") ?? "3");
  const format = values.get("format") ?? "compact";
  if (!Number.isInteger(maxConcurrentRunners) || maxConcurrentRunners < 2 || maxConcurrentRunners > 10) {
    throw new Error("--max-runners 必须是 2 到 10 的整数");
  }
  if (format === "compact") issueCompact(values, installId, expiresAt, maxConcurrentRunners);
  else if (format === "legacy") issueLegacy(values, installId, expiresAt, maxConcurrentRunners);
  else throw new Error("--format 只能是 compact 或 legacy");
}

const [command, ...args] = process.argv.slice(2);
const values = options(args);
try {
  if (command === "keygen") keygen(values);
  else if (command === "issue") issue(values);
  else throw new Error("用法: license.mjs keygen|issue [参数]");
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
